$('.owl-carousel').owlCarousel({
    loop:true,
    margin:55,
    nav:true,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:3
        },
        800:{
            items:3
        },
        1000:{
            items:4
        },
        1100:{
            items:4
        },
        1250:{
            items:4
        },
        1400:{
            items:4
        },
        1600:{
            items:4
        },
        1700:{
            items:5
        },
        1800:{
            items:7
        },
        
    }
})